version: "3"
services:
  backend-app:
    image: hamoudaatti/backdevops:latest
    restart: always
    ports:
      - "8082:8080"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    depends_on:
      - mysqldb

  mysqldb:
    container_name: mysqldb
    image: mysql
    restart: always
    volumes:
      - /opt/mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root

  frontend-app:
    image: hamoudaatti/frontdevops:latest
    restart: always
    ports:
      - "4200:4200"
    depends_on:
      - backend-app
