version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"  # Map host port 9090 to Prometheus's port 9090
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Mount your Prometheus configuration file
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  prometheus-data:
  grafana-data:

